// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA61_xRfUPNiBY9pIcDFxESL8Rsm2H3-LI',
    appId: '1:776338860055:web:2dacee7bf7de34f828d452',
    messagingSenderId: '776338860055',
    projectId: 'shikhito-app',
    authDomain: 'shikhito-app.firebaseapp.com',
    storageBucket: 'shikhito-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9MUT4_kWZJood40WqtOO3hOrbJYo0lA',
    appId: '1:776338860055:android:e2261d96fc9af1c528d452',
    messagingSenderId: '776338860055',
    projectId: 'shikhito-app',
    storageBucket: 'shikhito-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzN6GkhMhqdbvqli3anKHlmeAVG_AyA3E',
    appId: '1:776338860055:ios:5ad4719cb1c2f04f28d452',
    messagingSenderId: '776338860055',
    projectId: 'shikhito-app',
    storageBucket: 'shikhito-app.firebasestorage.app',
    iosBundleId: 'com.example.shikhitoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzN6GkhMhqdbvqli3anKHlmeAVG_AyA3E',
    appId: '1:776338860055:ios:5ad4719cb1c2f04f28d452',
    messagingSenderId: '776338860055',
    projectId: 'shikhito-app',
    storageBucket: 'shikhito-app.firebasestorage.app',
    iosBundleId: 'com.example.shikhitoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA61_xRfUPNiBY9pIcDFxESL8Rsm2H3-LI',
    appId: '1:776338860055:web:8182f8e48e91b2d228d452',
    messagingSenderId: '776338860055',
    projectId: 'shikhito-app',
    authDomain: 'shikhito-app.firebaseapp.com',
    storageBucket: 'shikhito-app.firebasestorage.app',
  );
}
